### ISSUE TITLE
Error during event retrieval in 6.0.0

### ISSUE THREAD

**Issue by samatgrow** [nylas/nylas-python#328]
**Describe the bug**
For some users, when querying events we get an error from the Python SDK:
```
Traceback (most recent call last):
  ...
  File "/venv/lib/python3.10/site-packages/nylas/resources/events.py", line 49, in list
    return super(Events, self).list(
  File "/venv/lib/python3.10/site-packages/nylas/handler/api_resources.py", line 15, in list
    return ListResponse.from_dict(response_json, response_type)
  File "/venv/lib/python3.10/site-packages/nylas/models/response.py", line 93, in from_dict
    converted_data.append(generic_type.from_dict(item))
  File "/venv/lib/python3.10/site-packages/dataclasses_json/api.py", line 70, in from_dict
    return _decode_dataclass(cls, kvs, infer_missing)
  File "/venv/lib/python3.10/site-packages/dataclasses_json/core.py", line 172, in _decode_dataclass
    field_value = kvs[field.name]
KeyError: 'read_only'
```

**To Reproduce**
Some steps involved to reproduce the bug and any code samples you can share.
```
for calendar in nylas_client.calendars.list(
    GRANT_ID,
    ListCalendersQueryParams(),
).data:
    for event in nylas_client.events.list(
        GRANT_ID,
        ListEventQueryParams(calendar_id=calendar.id)
    ).data:
        print(event)
```

**Expected behavior**
Events to be returned correctly.

**SDK Version:**
6.0.0b7

**Additional context**
Pulling the latest commit solves the issue, I think this bug was fixed in https://github.com/nylas/nylas-python/commit/09ae0d2ee25d02cd3348008af4936af53c131225

So I think we just need a v6.0.0b8 release and we'd be set.

**Comment by mrashed-dev** [comment]
This fix is now released in v6 beta 8: https://pypi.org/project/nylas/6.0.0b8/
